name: aggregator

on:
  push:
    branches:
      - 'main'
    paths:
      - 'aggregator/**'
      # Check for breaking changes from contracts
      - 'contracts/**'
      - '.github/workflows/aggregator.yml'
  pull_request:
    paths:
      - 'aggregator/**'
      # Check for breaking changes from contracts
      - 'contracts/**'
      - '.github/workflows/aggregator.yml'
    branches-ignore:
      # Changes targeting this branch should be tested+fixed when being merged
      # into main
      - contract-updates

defaults:
  run:
    working-directory: ./aggregator

env:
  DENO_VERSION: 1.x

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - run: deno lint .

  todos-fixmes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - run: ./programs/lintTodos.ts

  typescript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - run: ./programs/checkTs.ts

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - uses: ./.github/actions/setup-contracts-clients

    # Setup node & contracts
    - working-directory: ./contracts
      run: yarn start &
    - working-directory: ./contracts
      run: ./scripts/wait-for-rpc.sh

    - run: cp .env.local.example .env
    - run: deno test --allow-net --allow-env --allow-read
